// In this section, the index page elements of  the site have been called

const sectionsElement = $.querySelectorAll("section")
const aboutTitleElement = $.querySelector('.about__title')
const aboutCaptionElement = $.querySelector(".about__caption")
const aboutSloganElement = $.querySelector(".about__slogan")
const aboutSkillsElement = $.querySelector(".about__skills")
const upperSectionButtonsElement = $.querySelector(".about__buttons")
const aboutPictureElement = $.getElementById("aboutImage")
const socialWrapperElement = $.querySelector(".social__wrapper")
const aboutSocialElement = $.querySelector(".about__social")
const skillsWrapperElement = $.querySelector(".skills__wrapper")
const skillsContainerElement = $.getElementById("rowSkills")
const projectContainerElement = $.getElementById("rowProject")
const projectPagesElement = $.getElementById("rowPagination")